### ISSUE TITLE
11.1.2上弹出调试框是空白的

### ISSUE THREAD

**Issue by zhujieshan** [whf5566/UIDebuggingTool#1]

**Comment by zhujieshan** [comment]
但是旧方法可以用 
#if DEBUG
    id overlayClass = NSClassFromString(@"UIDebuggingInformationOverlay");
    [overlayClass performSelector:NSSelectorFromString(@"prepareDebuggingOverlay")];
#endif

**Comment by whf5566** [comment]
首次点击按钮弹出的调试框是空白的。
两个手指同时点击状态栏弹出调试框应该是好的。

如果需要使用toggleOverlay切换，可以自己实现toggleOverlay方法：
+ (void)toggleOverlay {
id debugInfoClass = NSClassFromString(@"UIDebuggingInformationOverlay");
id handlerClass = NSClassFromString(@"UIDebuggingInformationOverlayInvokeGestureHandler");
id debugOverlayInstance = [debugInfoClass performSelector:NSSelectorFromString(@"overlay")];
[debugOverlayInstance setFrame:[[UIScreen mainScreen] bounds]];
		
id handler = [handlerClass performSelector:NSSelectorFromString(@"mainHandler")];
[handler performSelector:NSSelectorFromString(@"_handleActivationGesture:") withObject:window];
}
