### ISSUE TITLE
crashes in iOS 13

### ISSUE THREAD

**Issue by futuretap** [whf5566/UIDebuggingTool#3]
There's a crash in [this line](https://github.com/whf5566/UIDebuggingTool/blob/1e9a9a44d3a9fd1e8ca967bed11001498e9b6bcd/UIDebuggingTool/UIDebuggingInformationOverlay%2BEnable.m#L92) on iOS 13 with this exception:

> App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.

**Comment by light-bo** [comment]
+1

**Comment by lmncomeon** [comment]
+1

**Comment by whf5566** [comment]
The status bar is no longer part of the application on iOS13, it’s part of the system UI (“springboard”).  The code is updated. Shake the phone to show UIDebuggingInformationOverlay.
